# Talk2Database — developer convenience targets.
# Run `make help` for the list.

.DEFAULT_GOAL := help
COMPOSE := docker compose

.PHONY: help up up-scheduled down logs build dev backend-dev frontend-dev \
        lint lint-backend lint-frontend test test-backend test-frontend \
        format migrate revision clean

help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-18s\033[0m %s\n", $$1, $$2}'

## ----- Docker bundle -----------------------------------------------------
up: ## Start the full stack (manual import mode)
	$(COMPOSE) up -d --build

up-scheduled: ## Start the full stack with the scheduled-sync cron service
	$(COMPOSE) --profile scheduled up -d --build

down: ## Stop and remove containers (keeps volumes/data)
	$(COMPOSE) down

build: ## Build all images
	$(COMPOSE) build

logs: ## Tail logs for all services
	$(COMPOSE) logs -f

## ----- Local development -------------------------------------------------
backend-dev: ## Run the backend with autoreload (needs local Postgres + .env)
	cd backend && uvicorn app.main:app --reload --port 8000

frontend-dev: ## Run the Vite dev server (proxies /api -> :8000)
	cd frontend && npm run dev

## ----- Quality gates -----------------------------------------------------
lint: lint-backend lint-frontend ## Lint + type-check everything

lint-backend: ## ruff + mypy
	cd backend && ruff check . && ruff format --check . && mypy app

lint-frontend: ## eslint + tsc
	cd frontend && npm run lint && npm run typecheck

format: ## Auto-format backend (ruff) and frontend (prettier)
	cd backend && ruff format . && ruff check --fix .
	cd frontend && npm run format

test: test-backend test-frontend ## Run all tests

test-backend: ## pytest
	cd backend && pytest

test-frontend: ## frontend unit tests
	cd frontend && npm test

## ----- Database migrations (panel DB) ------------------------------------
migrate: ## Apply Alembic migrations to the panel DB
	cd backend && alembic upgrade head

revision: ## Create a new autogenerated migration: make revision m="message"
	cd backend && alembic revision --autogenerate -m "$(m)"

clean: ## Remove caches and build artifacts
	rm -rf backend/.pytest_cache backend/.mypy_cache backend/.ruff_cache \
	       frontend/dist frontend/node_modules
